sudo: required
language: node_js
node_js:
  - "14"
services:
  - docker
before_install:
  - docker pull emscripten/emsdk:2.0.11
  - npm run prepare
before_script:
  - npm run clean
script:
  - npm run build:release
  - npm run test
before_deply: npm run clean:test
deploy:
  provider: npm
  email: yujianrong@gmail.com
  api_key:
    secure: oMY0IWBN49x7myS9TXYLZOmz/Xw9KbsRRSRe1O73DWAMrFbQic5y0JOMrWRY5FEGBYz2B12N+5E2t9xB511ldgY12Ru5wKXTWX7e38ENs8dub46rNdUe8es2NOtDleQMM2VFX94SvJrkzSKY5cvmTjtovn6XzBqwqpEMVIykuVa2F42L3tf9jQTPGYnXbkbFMipKSQwd2UfVGr4+U2LgcO8VsJ0c5+lgUVP8GqT5cp31FZ1t6QAdgXbGrhFDjBWSYH8b4ltQVYL2UGozSSMgcTd2FjML/GllDHRYeXGRrrTCkx6oaSyuG7fT0h5NJ/6Yt5vx0JQgL9pEd2iJTSXZicsiAlz9KWpD4ugAllzIvPILSAsuvrDxVfKvwi1aEid9qvvq/lO3p5peHna3tyeH2W91yR0PpcwJF55FvWPjFepRYg3epD0HQ8EPnT2iU0N2xu+UvZBS+QQB3QLOXDkYk/RDF41uoIABuId8EJy5DZxcqfNDOcgCbga6FFBeRW5W3UPoEb8eWZUg3X+G4u8gAUeBfeQ+VLf8BYj1rCn9yJiFcZTZsr9CwP/nEukbNV/2XhBHAc0R4f3W4lSvc0HMzHrDJkZcEkT7s7wEeWGk3yEzzS2V8tDLXJW8nlib6lLwAhi/u2mjVJ5vRX/ejSaXc7DHdqLWs359f9rTsrK/5kw=
  on:
    tags: true
    repo: YuJianrong/node-unrar.js
  skip_cleanup: "true"
